FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

RUN pip install --no-cache-dir \
    mlflow==2.17.0 \
    fastapi==0.115.0 \
    uvicorn[standard]==0.30.6 \
    prometheus-client==0.21.0 \
    numpy

COPY ../src/serve /app/serve
COPY ../src/utils /app/utils

ENV PYTHONPATH=/app

EXPOSE 8000

CMD ["uvicorn", "serve.app:app", "--host", "0.0.0.0", "--port", "8000"]


