FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY ../pyproject.toml /app/
RUN pip install poetry && \
    poetry export --without-hashes -f requirements.txt --output requirements.txt && \
    pip install -r requirements.txt && \
    rm requirements.txt

COPY ../src/serve /app/serve
COPY ../src/utils /app/utils

ENV PYTHONPATH=/app

EXPOSE 8000

CMD ["uvicorn", "serve.app:app", "--host", "0.0.0.0", "--port", "8000"]


